# Generated by Django 2.1.3 on 2018-12-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_auto_20181214_1435'),
        ('forum', '0005_auto_20181214_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_publisher', to='card.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_publisher', to='card.UserProfile'),
        ),
    ]
