# Generated by Django 2.1.1 on 2018-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_cout', models.IntegerField(default=0)),
                ('card_ptattaque', models.IntegerField(default=0)),
                ('card_ptvie', models.IntegerField(default=0)),
            ],
        ),
    ]
