# Generated by Django 2.1.1 on 2018-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20181026_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=255)),
                ('cards', models.ManyToManyField(blank=True, to='card.Card')),
            ],
        ),
    ]
