# Generated by Django 2.1.1 on 2018-11-10 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0006_auto_20181108_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(blank=True, to='card.Card')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='user',
        ),
        migrations.AlterField(
            model_name='deck',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='card.Collec'),
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
