# Generated by Django 2.1.1 on 2018-11-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20181110_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
