# Generated by Django 2.1.1 on 2018-11-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0013_auto_20181116_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_owners',
            field=models.ManyToManyField(related_name='cards', through='card.Collec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collec',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='collec',
            name='cards',
        ),
        migrations.AddField(
            model_name='collec',
            name='cards',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.Card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collec',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
