# Generated by Django 2.1.3 on 2018-11-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_auto_20181116_1409'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/card/'),
        ),
    ]
