# Generated by Django 2.1.3 on 2018-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_auto_20181127_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='card.UserProfile'),
        ),
    ]
