# Generated by Django 2.1.3 on 2018-12-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='my_following', to='card.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='card.UserProfile'),
        ),
    ]
